### ISSUE TITLE
Unable to connect with OAuth packages that doesn't use the standard naming convention

### ISSUE THREAD

**Issue by unbornchikken** [mondora/mondora-connect-with#6]
I'm trying to use with your module with [gcampax:accounts-dropbox](https://atmospherejs.com/gcampax/accounts-dropbox) which uses [gcampax:dropbox-oauth](https://atmospherejs.com/gcampax/dropbox-oauth) under the hood. I cannot use this with provided `connectWith` method, since there is no OAuth module to be found when I pass the name of the package as the argument, eg.:

```js
Meteor.connectWith("gcampax:dropbox-oauth");
```

Your module's gonna look for Package["gcampax:dropbox-oauth"]["Gcampax:dropbox-oauth"] on this case and it doesn't exists of course.

I created a PR to fix this issue: https://github.com/mondora/mondora-connect-with/pull/5

**Comment by pscanf** [comment]
#5 fixes this. Thanks
