### ISSUE TITLE
How to disconnect accounts? 

### ISSUE THREAD

**Issue by kulakowka** [mondora/mondora-connect-with#7]
I want disconnect connected accounts, how can i do this?

**Comment by pscanf** [comment]
Hi there. :-)

When a user connects his account to service `x`, an entry gets added to the user's document `services` subdocument:

``` js
{
    // ...
    "services": {
        "x": {
            // ...
        }
    }
}
```

The package does not provide a specific method to disconnect the service, but you can simply do it by deleting that entry:

``` js
Meteor.users.update({_id: userId}, {
    $unset: {
        "services.x": true
    }
});
```

Hope this helps.
Paolo
